In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/cafe_sales.csv')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [4]:
df.shape

(10000, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [6]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3,6,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [7]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [8]:
df = df.dropna(axis='columns',how='all')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              9667 non-null   object
 1   Quantity          9862 non-null   object
 2   Price Per Unit    9821 non-null   object
 3   Total Spent       9827 non-null   object
 4   Payment Method    7421 non-null   object
 5   Location          6735 non-null   object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [13]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              9667 non-null   object
 1   Quantity          9862 non-null   object
 2   Price Per Unit    9821 non-null   object
 3   Total Spent       9827 non-null   object
 4   Payment Method    7421 non-null   object
 5   Location          6735 non-null   object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [15]:
df = df.dropna(axis=0,how='all')
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              9667 non-null   object
 1   Quantity          9862 non-null   object
 2   Price Per Unit    9821 non-null   object
 3   Total Spent       9827 non-null   object
 4   Payment Method    7421 non-null   object
 5   Location          6735 non-null   object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [17]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [18]:
columns_to_fill = ['Item','Payment Method','Location']
for column_name in columns_to_fill:
  df.loc[df[column_name].isna(),column_name] = 'UNKNOWN'
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          9862 non-null   object
 2   Price Per Unit    9821 non-null   object
 3   Total Spent       9827 non-null   object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [20]:
cols_to_fill = ['Quantity','Price Per Unit','Total Spent']
for column_name in cols_to_fill:
  df.loc[df[column_name].isna(),column_name] = 0
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [22]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [24]:
df.tail(21)

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9979,Smoothie,5,4,20,Cash,In-store,7/20/2023
9980,Tea,4,1.5,6,UNKNOWN,UNKNOWN,8/24/2023
9981,ERROR,5,4,20,Digital Wallet,UNKNOWN,2/27/2023
9982,Cookie,2,1,2,UNKNOWN,Takeaway,12/30/2023
9983,Smoothie,3,4,12,Cash,UNKNOWN,UNKNOWN
9984,Smoothie,UNKNOWN,4,4,Cash,Takeaway,7/27/2023
9985,Cake,2,3,6,UNKNOWN,UNKNOWN,1/3/2023
9986,Sandwich,2,4,8,Credit Card,In-store,12/14/2023
9987,Juice,5,3,15,Cash,UNKNOWN,7/31/2023
9988,Cake,5,3,0,ERROR,UNKNOWN,NaN
9989,Juice,5,3,15,Cash,UNKNOWN,8/18/2023
9990,Coffee,5,2,10,Digital Wallet,UNKNOWN,5/22/2023
9991,Sandwich,3,4,12,Cash,Takeaway,2/24/2023
9992,Smoothie,4,4,16,UNKNOWN,In-store,7/5/2023
9993,Smoothie,2,4,0,Cash,UNKNOWN,10/20/2023
9994,UNKNOWN,4,4,16,UNKNOWN,UNKNOWN,1/8/2023
9995,Coffee,2,2,4,UNKNOWN,UNKNOWN,8/30/2023
9996,UNKNOWN,3,0,3,Digital Wallet,UNKNOWN,6/2/2023
9997,Coffee,4,2,8,Digital Wallet,UNKNOWN,3/2/2023
9998,Cookie,3,0,3,Digital Wallet,UNKNOWN,12/2/2023
9999,Sandwich,3,4,12,Cash,In-store,11/7/2023

In [25]:
col_to_fill = ['Transaction Date']
for column_name in col_to_fill:
  df.loc[df[column_name].isna(),column_name] = '2/21/2023'
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: object(7)
memory usage: 547.0+ KB

In [27]:
df.head(25)

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,Smoothie,5,4,20,Credit Card,UNKNOWN,3/31/2023
6,UNKNOWN,3,3,9,ERROR,Takeaway,10/6/2023
7,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,UNKNOWN,5,3,15,UNKNOWN,Takeaway,7/28/2023
9,Sandwich,5,4,20,UNKNOWN,In-store,12/31/2023
10,Salad,5,5,25,Cash,Takeaway,11/7/2023
11,Sandwich,2,4,8,Credit Card,Takeaway,ERROR
12,Sandwich,2,4,8,Cash,In-store,5/3/2023
13,Cookie,5,1,5,UNKNOWN,Takeaway,6/1/2023
14,ERROR,2,1.5,3,UNKNOWN,In-store,3/21/2023
15,Salad,3,5,15,Credit Card,In-store,11/15/2023
16,Sandwich,1,4,4,UNKNOWN,UNKNOWN,6/10/2023
17,Juice,2,3,6,Cash,In-store,2/24/2023
18,Cake,5,3,15,Cash,ERROR,3/25/2023
19,Juice,4,3,12,Cash,Takeaway,1/15/2023
20,Smoothie,ERROR,4,20,Cash,In-store,4/4/2023
21,Smoothie,4,4,16,Credit Card,Takeaway,3/30/2023
22,Sandwich,3,4,12,Digital Wallet,Takeaway,12/1/2023
23,Sandwich,2,4,8,UNKNOWN,UNKNOWN,9/18/2023
24,Sandwich,5,4,20,Cash,In-store,6/3/2023

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: object(7)
memory usage: 547.0+ KB

In [30]:
df.isnull().sum()

Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [31]:
df.shape

(10000, 7)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: object(7)
memory usage: 547.0+ KB

In [33]:
df.head(15)

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,Smoothie,5,4,20,Credit Card,UNKNOWN,3/31/2023
6,UNKNOWN,3,3,9,ERROR,Takeaway,10/6/2023
7,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,UNKNOWN,5,3,15,UNKNOWN,Takeaway,7/28/2023
9,Sandwich,5,4,20,UNKNOWN,In-store,12/31/2023
10,Salad,5,5,25,Cash,Takeaway,11/7/2023
11,Sandwich,2,4,8,Credit Card,Takeaway,ERROR
12,Sandwich,2,4,8,Cash,In-store,5/3/2023
13,Cookie,5,1,5,UNKNOWN,Takeaway,6/1/2023
14,ERROR,2,1.5,3,UNKNOWN,In-store,3/21/2023

In [34]:
df['Item'] = df['Item'].replace('ERROR','UNKNOWN')
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [35]:
df.head(15)

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,Smoothie,5,4,20,Credit Card,UNKNOWN,3/31/2023
6,UNKNOWN,3,3,9,ERROR,Takeaway,10/6/2023
7,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,UNKNOWN,5,3,15,UNKNOWN,Takeaway,7/28/2023
9,Sandwich,5,4,20,UNKNOWN,In-store,12/31/2023
10,Salad,5,5,25,Cash,Takeaway,11/7/2023
11,Sandwich,2,4,8,Credit Card,Takeaway,ERROR
12,Sandwich,2,4,8,Cash,In-store,5/3/2023
13,Cookie,5,1,5,UNKNOWN,Takeaway,6/1/2023
14,UNKNOWN,2,1.5,3,UNKNOWN,In-store,3/21/2023

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: object(7)
memory usage: 547.0+ KB

In [64]:
df.isnull().sum()

Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [39]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [40]:
df['Total Spent'] = df['Total Spent'].replace('ERROR',np.nan)
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,NaN,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  float64
 3   Total Spent       10000 non-null  float64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 547.0+ KB

In [45]:
df['Total Spent'] = df['Total Spent'].fillna(0)
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,0,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  object
 2   Price Per Unit    10000 non-null  object
 3   Total Spent       10000 non-null  object
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: object(7)
memory usage: 547.0+ KB

In [47]:
df.isnull().sum()

Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [49]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,0,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [65]:
numerical_cols = ['Quantity','Price Per Unit','Total Spent']
for col in numerical_cols:
  df[col] = pd.to_numeric(df[col],errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  float64
 3   Total Spent       10000 non-null  float64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 547.0+ KB

In [69]:
df['Total Spent'] = df['Total Spent'].fillna(0).astype('int64')
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,0,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          9659 non-null   float64
 2   Price Per Unit    9646 non-null   float64
 3   Total Spent       10000 non-null  int64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 547.0+ KB

In [68]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(0).astype('int64')
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4.0,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12.0,Cash,In-store,5/16/2023
2,Cookie,4,1,0.0,Credit Card,In-store,7/19/2023
3,Salad,2,5,10.0,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4.0,Digital Wallet,In-store,6/11/2023

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          9659 non-null   float64
 2   Price Per Unit    10000 non-null  int64
 3   Total Spent       10000 non-null  int64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 547.0+ KB

In [70]:
df['Quantity'] = df['Quantity'].fillna(0).astype('int64')
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,Cake,4,3,12,Cash,In-store,5/16/2023
2,Cookie,4,1,0,Credit Card,In-store,7/19/2023
3,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  object
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  int64
 3   Total Spent       10000 non-null  int64
 4   Payment Method    10000 non-null  object
 5   Location          10000 non-null  object
 6   Transaction Date  10000 non-null  object
dtypes: int64(3), object(4)
memory usage: 547.0+ KB

In [73]:
type_dict = {
    'Transaction Date':'datetime64[ns]',
    'Item':'category',
    'Payment Method':'category',
    'Location':'category',
    'Quantity':'int64',
    'Price Per Unit':'int64',
    'Total Spent':'int64'
}

df['Transaction Date'] = df['Transaction Date'].replace('ERROR', '2/21/2023')
df['Transaction Date'] = df['Transaction Date'].replace('UNKNOWN', '2/21/2023')
for key, value in type_dict.items():
  df[key] = df[key].astype(value)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  category
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  int64
 3   Total Spent       10000 non-null  int64
 4   Payment Method    10000 non-null  category
 5   Location          10000 non-null  category
 6   Transaction Date  10000 non-null  datetime64[ns]
dtypes: category(3), datetime64[ns](1), int64(3)
memory usage: 342.7 KB

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              10000 non-null  category
 1   Quantity          10000 non-null  int64
 2   Price Per Unit    10000 non-null  int64
 3   Total Spent       10000 non-null  int64
 4   Payment Method    10000 non-null  category
 5   Location          10000 non-null  category
 6   Transaction Date  10000 non-null  datetime64[ns]
dtypes: category(3), datetime64[ns](1), int64(3)
memory usage: 342.7 KB

In [83]:
df.describe()

           Quantity  Price Per Unit   Total Spent            Transaction Date
count  10000.000000    10000.000000  10000.000000                       10000
mean       2.883400        2.736100      8.443000  2023-06-25 22:25:49.440000
min        0.000000        0.000000      0.000000         2023-01-01 00:00:00
25%        2.000000        1.000000      4.000000         2023-03-19 00:00:00
50%        3.000000        3.000000      7.000000         2023-06-24 00:00:00
75%        4.000000        4.000000     12.000000         2023-09-27 00:00:00
max        5.000000        5.000000     25.000000         2023-12-31 00:00:00
std        1.528214        1.469038      6.194739                         NaN

In [84]:
df.to_csv('Cafe_Sales.csv',index=False)